version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: accounts-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    ports:
      - "3307:3306"
    volumes:
      - accounts_mysql_data:/var/lib/mysql

volumes:
  accounts_mysql_data:
